### ISSUE TITLE
Best Model

### ISSUE THREAD

**Issue by bernhard2202** [unilight/R-NET-in-Tensorflow#4]
Could you maybe make the best model accessible for download? 
I tried to reach your results but I struggle with the default configuration to do so.

**Comment by unilight** [comment]
Hi @bernhard2202 , 

The goal of this repo is to reproduce the result using the architecture described in the original paper, so instead of providing trained model weights, I think it's more important for everyone to be able to reproduce the result. What's your current best result? Maybe I can check what I'm missing in the repo. 😃

**Comment by bernhard2202** [comment]
by training on the master-branch as it is without any modifications I get

`{"exact_match": 53.85052034058656, "f1": 63.47486216568919}`

I would like to evaluate R-NET for some different datasets. Maybe it would be helpful for others as well, if you upload and update the model that achieved the best score so far.

**Comment by unilight** [comment]
@bernhard2202 How many epochs did you train? Train for more epochs and see when the model converges.

**Comment by bernhard2202** [comment]
12 Epochs. If you don't want to upload the best model, could you maybe update the hyperparameter file and give instructions on how many epochs you needed to achieve this score in your ReadMe? Its a bit expensive to play around with hyperparameters on models that train for several hours on GPUs.

**Comment by unilight** [comment]
@bernhard2202 I have released a set of trained model parameters. Checkout the README!

**Comment by bernhard2202** [comment]
Awesome thanks a lot!
